---
title: "iteration"
author: "Yiyao LI"
date: "2020/11/11"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
set.seed(1)
```

## lists

you can put everything in a list
```{r}
l = list(
  vec_numeric = 5:8,
  mat = matrix(1:8, nrow = 2, ncol = 4),
  vec_logical = c(TRUE, FALSE),
  summary     = summary(rnorm(100)))
l
```

```{r}
l
l$vec_numeric
l[[1]]
mean(l[["vec_numeric"]])
```

## for loop

creat a new list

```{r}
list_norm = 
  list(
    a = rnorm(20, mean = 3, sd = 1),
    b = rnorm(30, mean = 0, sd = 5),
    c = rnorm(40, mean = 10, sd = .2),
    d = rnorm(20, mean = -3, sd = 1)
  )
```

get my old function

```{r}
mean_and_sd = function(x){
  
  if(!is.numeric(x)){
    stop("Input must be numeric")
  }
  
  if(length(x)<3){
    stop("Input must have at least 3 numbers")
  }
 
   mean_x = mean(x)
   sd_x = sd(x)
   
   tibble(
     mean_x, sd_x
   )
  
}

```

apply that function to each list element

```{r}
mean_and_sd(list_norm[[1]])
mean_and_sd(list_norm[[2]])
mean_and_sd(list_norm[[3]])
mean_and_sd(list_norm[[4]])
```

let's use for loop
first make empty list

```{r}
output = vector("list", length = 4)

for (i in 1:4){
  output[[1]] = mean_and_sd(list_norm[[i]])
}
```

