---
title: "Untitled"
author: "Yiyao LI"
date: "2020/11/13"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
```

## Let's simulate sth

function

```{r}
sim_mean_sd = function(n, mu = 2, sigma = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  sim_data %>% 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}
```

simulate by this line

```{r}
sim_mean_sd(30)
```

simulate a lot

```{r}
output = vector("list", length = 100)

for (i in 1:100){
  output[[i]] = sim_mean_sd(30)
}

bind_rows(output)
```

loop function

```{r}
sim_results = 
  rerun(100,sim_mean_sd(30)) %>% 
  bind_rows()
```

check

```{r}
sim_results %>% 
  ggplot(aes(x = mu_hat))+geom_density()

sim_results %>% 
  summarize(
    avg_mean = mean(mu_hat),
    avg_sd = mean(sigma_hat)
  )


```

other samples

```{r}
n_list = 
  list(
    "n_30"  = 30, 
    "n_60"  = 60, 
    "n_120" = 120, 
    "n_240" = 240)

output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = rerun(100, sim_mean_sd(n_list[[i]])) %>% 
    bind_rows
}
```

```{r}
sim_results = 
  tibble(sample_size = c(30, 60, 120, 240)) %>% 
  mutate(
    output_lists = map(.x = sample_size, ~rerun(1000, sim_mean_sd(n = .x))),
    estimate_dfs = map(output_lists, bind_rows)) %>% 
  select(-output_lists) %>% 
  unnest(estimate_dfs)
```

data frame thing

```{r}
sim_results %>% 
  mutate(
    sample_size = str_c("n = ", sample_size),
    sample_size = fct_inorder(sample_size)) %>% 
  ggplot(aes(x = sample_size, y = mu_hat, fill = sample_size))+
  geom_violin()
```

```{r}
sim_results %>% 
  group_by(sample_size) %>% 
  summarize(
    avg_mean = mean(mu_hat),
    avg_sd = sd(sigma_hat)
  )
```

